/*
 * robot_config.h
 *
 * Every tunable value for the robot, in one place.
 * During calibration this is the only file you should need to edit.
 * Values marked [CAL] are the ones Phase 5 calibration adjusts.
 *
 * Nothing here is generated by CubeMX, so regenerating the .ioc never
 * touches it.
 */
#ifndef ROBOT_CONFIG_H
#define ROBOT_CONFIG_H

/* ==========================================================================
 *  1. BUILD SWITCHES  - check these before every task run
 * ========================================================================== */

/* Which floor the robot runs on. Set on task day, once the arena is announced.
 *   0 = indoor  (lab floor)            - calibrated
 *   1 = outdoor (tiled corridor)       - NOT calibrated yet, see section 2   */
#define ARENA_OUTDOOR       0

/* Knob-and-button test modes (SD straights, TN turns) and the TD / TV serial
 * commands. Needed for calibration. Set to 0 for the actual task run, so the
 * user button can never start a test move.                                 */
#define FIELD_TOOLS         0

/* Replies to the RPi. 0 = short ("A d=99.9 e=+0.4"), 1 = full diagnostics.
 * The TD log always has the full diagnostics either way.                   */
#define DEBUG_REPLIES       0


/* ==========================================================================
 *  2. FLOOR-DEPENDENT VALUES  - one set per arena type
 *     Grip and slope differ between floors, so these are calibrated per floor.
 * ========================================================================== */
#if ARENA_OUTDOOR == 0
/* ---- INDOOR (lab floor) ---- */
  #define TICKS_PER_CM        75.5f   // [CAL] Encoder ticks per cm (measured by tape)
  #define STOP_T              0.050f  // [CAL] Straights: robot rolls this many seconds after deciding to stop
  #define TURN_STOP_T         0.075f  // [CAL] Turns: robot keeps rotating this many seconds after deciding to stop
  #define TURN_RADIUS_L       20.2f   // [CAL] Left-lock turning radius at the rear-axle centre (cm), LF180 diameter
  #define TURN_RADIUS_R       36.2f   // [CAL] Right-lock turning radius (cm), RF180 diameter
  #define SERVO_TRUE_CENTRE   1504    // [CAL] Servo value for straight ahead (approached from below)
  #define MOTOR_FF_BASE       2100.0f // [CAL] PWM that just keeps the robot rolling (Phase 2 floor test)
  #define MOTOR_KICK_PWM      3300.0f // [CAL] Start burst; must beat the worst start seen (3205)
  #define SPEED_PROFILE       2       // [CAL] See section 4
#else
/* ---- OUTDOOR (tiled corridor) ----
 * Calibrated 1 Oct 2026 on the corridor tiles: all values as indoors, except
 * the radii (measured 20.0 / 35.9) and the centre (1500 tested straight).
 * Expect 1-3 cm/m of sideways drift from the slope and grout lines.         */
  #define TICKS_PER_CM        75.5f
  #define STOP_T              0.050f
  #define TURN_STOP_T         0.075f
  #define TURN_RADIUS_L       20.0f
  #define TURN_RADIUS_R       35.9f
  #define SERVO_TRUE_CENTRE   1500
  #define MOTOR_FF_BASE       2100.0f
  #define MOTOR_KICK_PWM      3300.0f
  #define SPEED_PROFILE       2
#endif


/* ==========================================================================
 *  3. ROBOT GEOMETRY AND STEERING  - the same on every floor
 * ========================================================================== */
#define TRACK_CM            15.7f   // Rear track, wheel centre to wheel centre (cm)
#define DEG2RAD             0.0174533f

#define SERVO_LEFT_LOCK     940     // Full left lock (us), 25 us clear of the 915 mechanical limit
#define SERVO_RIGHT_LOCK    2080    // Full right lock (us), 20 us clear of the 2100 limit
#define SERVO_APPROACH_US   40      // Centre is always approached from this far below (servo slack)
#define TURN_IO_L           0.50f   // Inner / outer rear wheel speed ratio at the left lock (measured)
#define TURN_IO_R           0.67f   // ... at the right lock

#define STEER_RIGHT_GAIN    1.3f    // [CAL] Right steering is weaker per us than left, so heading
                                    //       corrections to the right are scaled up by this much.
                                    //       x1.0 drifted left (+1.7 deg), x1.6 drifted right (-1.55).
#define STEER_PLAY_US       15.0f   // [CAL] Steering play compensation: when a correction reverses,
                                    //       the servo jumps this far across the play (0 = off).
                                    //       Real play ~20-40 us. MUST stay below the real play,
                                    //       or the wheels start hopping back and forth.


/* ==========================================================================
 *  4. SPEEDS
 *     Every stop finishes from the slow approach speed, so accuracy barely
 *     depends on the cruise speed. Confirm on the robot after any change.
 * ========================================================================== */
/* Turns speed up and slow down at the SAME rate, which keeps the turn's
 * path symmetric. Measured: a 180 deg turn ends within ~1-3 cm of its start
 * line (measure axle to axle - a tyre's back edge moves 6.7 cm after 180). */
#if SPEED_PROFILE == 0
  #define STRAIGHT_V_MAX    35.0f   // Straight cruise speed (cm/s)
  #define TURN_V_MAX        25.0f   // Turn cruise speed at the rear-axle centre (cm/s)
  #define STRAIGHT_ACCEL    60.0f   // Straights: speeding up (cm/s per second)
  #define STRAIGHT_DECEL    50.0f   // Straights: slowing down (cm/s per second)
  #define TURN_ACCEL        50.0f   // Turns: speeding up and ...
  #define TURN_DECEL        50.0f   // ... slowing down - keep these equal
#elif SPEED_PROFILE == 1
  #define STRAIGHT_V_MAX    50.0f
  #define TURN_V_MAX        35.0f
  #define STRAIGHT_ACCEL    80.0f
  #define STRAIGHT_DECEL    70.0f
  #define TURN_ACCEL        70.0f
  #define TURN_DECEL        70.0f
#else  /* 2 = fastest with no accuracy loss in simulation */
  #define STRAIGHT_V_MAX    65.0f
  #define TURN_V_MAX        45.0f
  #define STRAIGHT_ACCEL    100.0f
  #define STRAIGHT_DECEL    60.0f   // [CAL] was 90: tyres skidded ~1 cm while slowing from 65 cm/s (Step 2)
  #define TURN_ACCEL        60.0f   // [CAL] equal to TURN_DECEL (symmetric turns)
  #define TURN_DECEL        60.0f   // [CAL]
#endif
#define STRAIGHT_V_MIN      12.0f   // Slowest speed used: above the stick-slip region
#define STRAIGHT_APPROACH   2.0f    // Last few cm of a straight are driven at STRAIGHT_V_MIN
#define TURN_V_MIN          14.0f   // Slowest turn speed: keeps the inner wheel above stick-slip
#define TURN_APPROACH_CM    4.0f    // Last few cm of arc of a turn are driven at TURN_V_MIN
#define TURN_SETTLE_MS      300     // Time for the servo to swing from centre to a lock


/* ==========================================================================
 *  5. MOTOR SPEED CONTROL
 * ========================================================================== */
/* Speed per PWM for each wheel and direction (cm/s per PWM, Phase 2) */
#define GAIN_L_FWD          0.0226f
#define GAIN_R_FWD          0.0196f
#define GAIN_L_REV          0.0179f
#define GAIN_R_REV          0.0193f
#define KICK_AFTER_LOOPS    3       // Start burst if a wheel hasn't turned for this many 10 ms loops
#define MOTOR_PWM_MAX       6500.0f // Stay below the non-linear top end (ARR is 7199)
#define PWM_BRAKE           7200    // Compare value above ARR = pin held high; both pins high = brake
#define WHEEL_KP            120.0f  // PWM per (tick / 10 ms) of speed error
#define WHEEL_KI            3.0f    // PWM added per tick of error, every 10 ms
#define WHEEL_I_LIMIT       1500.0f // Integral term limit (PWM)
#define BRAKE_ASSIST_TICKS  5.0f    // Straights, while slowing: brake both wheels if this much too fast
#define TURN_ASSIST_TICKS   3.0f    // Turns, while slowing: brake both wheels if this much too fast


/* ==========================================================================
 *  6. HEADING CONTROL
 * ========================================================================== */
#define HEADING_KP_US       11.0f   // Servo us per degree of heading error
#define HEADING_MAX_US      60.0f   // Largest heading correction (us)
#define SERVO_RATE_US       4.0f    // Largest servo change per 10 ms (keeps it smooth)
#define HEADING_KI_US       0.01f   // Centre learning: us per degree of error, per 10 ms
#define SERVO_TRIM_MAX      30.0f   // Learned centre may move at most this far from SERVO_TRUE_CENTRE
#define STRAIGHT_KY         0.9f    // Line holding: degrees of correction per cm of sideways drift
#define STRAIGHT_KY_FADE    25.0f   // Line holding fades out over the last this-many cm
#define TURN_W_ALPHA        0.4f    // Yaw-rate smoothing for the turn stop decision (1 = none)


/* ==========================================================================
 *  7. FIELD TOOLS (only used when FIELD_TOOLS = 1)
 * ========================================================================== */
#define KNOB_US_MIN         900     // Knob fully clockwise
#define KNOB_US_MAX         2200    // Knob fully anticlockwise
#define TEST_LOG_SIZE       40      // Results kept for the TD command
#define BTN_LONG_MS         800     // Hold the button this long to switch SD / TN
#define TV_MIN              800     // Allowed range for the TV command
#define TV_MAX              2200


/* ==========================================================================
 *  7b. ULTRASONIC SENSOR (HC-SR04) - calibrated with the 10x10 cm obstacle block
 * ========================================================================== */
#define ULTRA_CM_PER_US     0.017673f // [CAL] cm per microsecond of echo (speed of sound + clock)
#define ULTRA_OFFSET_CM     0.65f     // [CAL] fixed offset (cm), measured from the sensor face


/* ==========================================================================
 *  8. IR DISTANCE SENSORS (Sharp GP2Y0A21YK0F, 10-80 cm)
 *     Power them from 5 V (4.5-5.5 V). Output is ~0.4 V (80 cm) to ~3.1 V (10 cm).
 * ========================================================================== */
#define OLED_SHOW_IR        1       // 1 = OLED shows the IR sensors instead of the encoder totals
#define IR1_ADC_CHANNEL     ADC_CHANNEL_14   // IR1 on PC4 (ADC1 channel 14)
#define IR2_ADC_CHANNEL     ADC_CHANNEL_5    // IR2 on PA5 (ADC1 channel 5)
#define IR_SAMPLES          8       // ADC readings averaged per update (the output is noisy)
/* Distance (cm) = IR_FIT_A x volts ^ IR_FIT_B. Fitted to the datasheet's typical
 * curve; each sensor differs by up to ~10%, so check against a ruler later. */
#define IR_FIT_A            27.5f
#define IR_FIT_B            (-1.21f)

#endif /* ROBOT_CONFIG_H */
